name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: 0 0 * * *

jobs:
  validate_hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.0
      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master  
  validate_hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.0
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
